# Site
name: "Okteto Community India"
title: "Okteto Community India "
description: " The Kubernetes development platform - Empower developers to innovate and deliver cloud-native applications faster than ever."
logo: 'assets/images//okteto-bangalore-logo-transparent.svg'
favicon: 'assets/images/logo.png'
baseurl: /community
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowth'
include: ["_pages"]
permalink: /:title/
email: 

# Authors
authors:
  sal:
    name: sangam 
    display_name: sangam 
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: sangambiradar@hotmail.com
    web: https://www.kubedaily.com
    twitter: https://twitter.com/BiradarSangam
    description: "Okteto Community Leader."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
